- filename: DBLP.bib
  search_type: FEED
  source_name: Decision Support Systems
  source_url: ''
  search_parameters: 
    - endpoint: dblp
      params: SCOPE venue_key='journals/dss' AND journal_abbreviated='Decis. Support Syst.'
  comment: ''
- filename: pdfs.bib
  search_type: PDFS
  source_name: DSS
  source_url: pdfs
  search_parameters: NA
  comment: NA
  outlet: journal=Decision Support Systems
  sub_dir_pattern: volume_number
- filename: CROSSREF.bib
  search_type: FEED
  source_name: Decision Support Systems
  source_url: ''
  search_parameters: 
    - endpoint: crossref
      params: SCOPE journal_issn='0167-9236'