- filename: DBLP.bib
  search_type: FEED
  source_name: Decision Support Systems
  source_url: ''
  search_parameters: 
    - endpoint: dblp
      params: SCOPE venue_key='journals/dss' AND journal_abbreviated='Decis. Support Syst.'
  comment: ''
- filename: CROSSREF.bib
  search_type: FEED
  source_name: Decision Support Systems
  source_url: ''
  search_parameters: 
    - endpoint: crossref
      params: SCOPE journal_issn='0167-9236'
- filename: pdfs.bib
  search_type: FEED
  source_name: DSS
  source_url: pdfs
  search_parameters:
  - endpoint: pdfs_directory
    params: SCOPE path='pdfs' WITH journal='Decision Support Systems' AND sub_dir_pattern='volume_number'
  comment: NA